### PR TITLE
Right-click cursor tp fix & Lock Border Improvement

### PR DESCRIPTION
**Pull request by zzahkaboom24**
Closing: #15

With this Pull Request, I am implementing a third feature to fix the teleportation of the mouse cursor upon holding the right-click key and dragging. It might not work 100% the same like the official roblox client, but I tried my best replicating it. That being said, it might not work 100% of the time, but you can also test to see wether it works or not

I am also improving the Lock Border feature to keep and teleport the mouse further to the border of the window instead of ~20-30 pixels inside the window allowing for more room, however the top is a complicated area which I improved a bit, but mostly left out the way it was because I realized upon testing that it can get stuck at the very top and this can be especially annoying in fullscreen mode. 

With the changed values for Lock Border, I also took the same logic from there and added it to my third feature to confine the mouse cursor as well while fixing the teleportation issue when right-clicking and dragging the avatars' camera.

If there are any bugs to fix or improvements to have to make, please let me know so I can try further looking into it. I am kinda new to programming so I tried what I could achieve and did not have a lot of time to deeply test this out because of that.

Before PR:

https://github.com/mengdeveloper/microsoftrbx-cursor-fix/assets/42496614/81ee14e7-1bb1-4545-9639-03957cd0fe5d

After PR:

https://github.com/mengdeveloper/microsoftrbx-cursor-fix/assets/42496614/254792a4-ec77-405d-b080-370f3c098442

### CODE REVIEW

**Comment by zzahkaboom24** [comment]
#15

**Review by keplerHaloxx — APPROVED** [review]
cant be bothered testing it but seems good 👍

**Comment by zzahkaboom24** [comment]
kk. If anything looks/behaves buggy or people report that, I will look into it and fix the issues in a separate pr trying to take care of those things

**Comment by mengdeveloper** [comment]
Looking good i'll build it

**Pull request merged**
